<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="GamepadTypes.fs" />
    <Compile Include="GamepadHost.fs" />
    <Compile Include="UnsupportedGamepadHost.fs" />
    <Compile Include="Platforms\macOS\MacOSGamepadHost.fs" />
    <Compile Include="GamepadHosts.fs" />
  </ItemGroup>

</Project>
