<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="Hardware.fs" />
    <Compile Include="Cartridge.fs" />
    <Compile Include="CartridgeMemory.fs" />
    <Compile Include="Interrupt.fs" />
    <Compile Include="Timer.fs" />
    <Compile Include="Lcd.fs" />
    <Compile Include="Joypad.fs" />
    <Compile Include="Apu.fs" />
    <Compile Include="Bus.fs" />
    <Compile Include="Cpu.fs" />
    <Compile Include="Video.fs" />
    <Compile Include="Emulator.fs" />
  </ItemGroup>

</Project>
